sudo: required

services:
  - docker

branches:
  only:
    - master
    - release
    - /^f_2.1.0.*$/

before_install:
  - sudo service mysql stop
  - docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3306:3306 -d mysql:5.7
  - sudo apt-get update && sudo apt-get install libunwind8
  - cp test/EFCore.MySql.FunctionalTests/config.json.example test/EFCore.MySql.FunctionalTests/config.json
  - cp test/EFCore.MySql.IntegrationTests/config.json.example test/EFCore.MySql.IntegrationTests/config.json
  - ./run.sh install-tools
  - ./dotnet-run.sh ./test/EFCore.MySql.IntegrationTests/scripts/rebuild.sh

script:
  # KoreBuild disabled due to failing Functional Tests
  # - ./build.sh
  - echo "Tests" && ./dotnet-run.sh dotnet test test/EFCore.MySql.Tests
  # Too many Functional Tests failing; fix before re-enabling in CI
  # - echo "Functional Tests" && ./dotnet-run.sh dotnet test -c Release test/EFCore.MySql.FunctionalTests
  - echo "Functional Migration Tests" && ./dotnet-run.sh dotnet test -c Release test/EFCore.MySql.FunctionalTests --filter "FullyQualifiedName~Pomelo.EntityFrameworkCore.MySql.FunctionalTests.MigrationSqlGeneratorMySqlTest|FullyQualifiedName~Pomelo.EntityFrameworkCore.MySql.FunctionalTests.MigrationSqlGeneratorMySql55Test|FullyQualifiedName~Pomelo.EntityFrameworkCore.MySql.FunctionalTests.OptimisticConcurrencyMySqlTest"
  - echo "Integration Tests applying migrations" && ./dotnet-run.sh dotnet run --project test/EFCore.MySql.IntegrationTests -c Release testMigrate
  - echo "Integration Tests scaffolding" && ./dotnet-run.sh ./test/EFCore.MySql.IntegrationTests/scripts/scaffold.sh
  - echo "Remove scaffolding files" && rm -rf ./test/EFCore.MySql.IntegrationTests/Scaffold
  - echo "Integration Tests with EF_BATCH_SIZE=1" && ./dotnet-run.sh dotnet test -c Release test/EFCore.MySql.IntegrationTests
  - echo "Integration Tests with EF_BATCH_SIZE=10" && ./dotnet-run.sh dotnet test -c Release test/EFCore.MySql.IntegrationTests
  - echo "Integration Tests with EF_RETRY_ON_FAILURE=3" && export EF_RETRY_ON_FAILURE="3" && ./dotnet-run.sh dotnet test -c Release test/EFCore.MySql.IntegrationTests
  - echo "Integration Tests legacy migrations" && ./dotnet-run.sh ./test/EFCore.MySql.IntegrationTests/scripts/legacy.sh
  - echo "Integration Tests Building migrations with EF_DATABASE=pomelo_test2" && export EF_SCHEMA="pomelo_test2" && ./dotnet-run.sh ./test/EFCore.MySql.IntegrationTests/scripts/rebuild.sh
  - echo "Integration Tests with EF_SCHEMA=pomelo_test2" && export EF_SCHEMA="pomelo_test2" && ./dotnet-run.sh dotnet test -c Release test/EFCore.MySql.IntegrationTests

notifications:
  email: false
