image: Visual Studio 2017
clone_depth: 1

services:
  - mysql

build_script:
  - ps: cp test\EFCore.MySql.FunctionalTests\config.json.example test\EFCore.MySql.FunctionalTests\config.json
  - ps: cp test\EFCore.MySql.IntegrationTests\config.json.example test\EFCore.MySql.IntegrationTests\config.json
  - ps: .\run.ps1 install-tools
  - ps: .\dotnet-run.ps1 .\test\EFCore.MySql.IntegrationTests\scripts\rebuild.ps1

test_script:
  # KoreBuild disabled due to failing Functional Tests
  # - .\build.cmd
  - ps: echo "Tests"; .\dotnet-run.ps1 dotnet test test\EFCore.MySql.Tests
  # Too many Functional Tests failing; fix before re-enabling in CI
  # - echo "Functional Tests"; .\dotnet-run.ps1 dotnet test -c Release test\EFCore.MySql.FunctionalTests
  - ps: echo "Functional Migration Tests"; .\dotnet-run.ps1 dotnet test -c Release test\EFCore.MySql.FunctionalTests --filter "FullyQualifiedName~Pomelo.EntityFrameworkCore.MySql.FunctionalTests.MigrationSqlGeneratorMySqlTest|FullyQualifiedName~Pomelo.EntityFrameworkCore.MySql.FunctionalTests.MigrationSqlGeneratorMySql55Test|FullyQualifiedName~Pomelo.EntityFrameworkCore.MySql.FunctionalTests.OptimisticConcurrencyMySqlTest"
  - ps: echo "Integration Tests applying migrations"; .\dotnet-run.ps1 dotnet run --project test\EFCore.MySql.IntegrationTests -c Release testMigrate
  - ps: echo "Integration Tests with EF_BATCH_SIZE=1"; .\dotnet-run.ps1 dotnet test -c Release test\EFCore.MySql.IntegrationTests
  - ps: echo "Integration Tests with EF_BATCH_SIZE=10"; .\dotnet-run.ps1 dotnet test -c Release test\EFCore.MySql.IntegrationTests
  - ps: echo "Integration Tests with EF_RETRY_ON_FAILURE=3"; $env:EF_RETRY_ON_FAILURE="3"; .\dotnet-run.ps1 dotnet test -c Release test\EFCore.MySql.IntegrationTests
  - ps: echo "Integration Tests Building migrations with EF_DATABASE=pomelo_test2"; $env:EF_SCHEMA="pomelo_test2"; .\dotnet-run.ps1 .\test\EFCore.MySql.IntegrationTests\scripts\rebuild.ps1
  - ps: echo "Integration Tests with EF_SCHEMA=pomelo_test2"; $env:EF_SCHEMA="pomelo_test2"; .\dotnet-run.ps1 dotnet test -c Release test\EFCore.MySql.IntegrationTests

deploy: off
